Update build.yml
Signed-off-by: S M Mahbub Hossain  <118460787+smmahbubhossain@users.noreply.github.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,5 +1,14 @@
 name: Build Modules
-on: [workflow_call, workflow_dispatch]
+on:
+  workflow_call:
+    secrets:
+      TELEGRAM_TOKEN:
+        description: "Telegram Bot Token"
+        required: true
+      TELEGRAM_TO:
+        description: "Telegram Chat ID"
+        required: true
+  workflow_dispatch:
 
 jobs:
   run:
@@ -22,7 +31,7 @@ jobs:
         uses: oprypin/find-latest-tag@v1
         continue-on-error: true
         with:
-          token: ${{ secrets.GH_TOKEN }}
+          token: ${{ secrets.GITHUB_TOKEN }}
           repository: ${{ github.repository }}
           releases-only: true
 
@@ -36,7 +45,7 @@ jobs:
       - name: Build modules/APKs
         run: ./build.sh
         env:
-          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GITHUB_REPOSITORY: $GITHUB_REPOSITORY
           NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
 
@@ -50,17 +59,13 @@ jobs:
           cp -f build.md build.tmp
 
           yt_op=$(find build -maxdepth 1 -name "youtube-*-magisk-*.zip" -printf '%P\n')
-          if [ -z "$yt_op" ]; then
-            echo "RELEASE_NAME=ReVanced" >> $GITHUB_OUTPUT
-          else
-            echo "RELEASE_NAME=$yt_op" >> $GITHUB_OUTPUT
-          fi
+          echo "RELEASE_NAME=$(date +'v%Y-%m-%d')" >> $GITHUB_OUTPUT
 
       - name: Upload modules to release
         uses: svenstaro/upload-release-action@v2
         with:
           body: ${{ steps.get_output.outputs.BUILD_LOG }}
-          repo_token: ${{ secrets.GH_TOKEN }}
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
           file: ./build/*
           release_name: ${{ steps.get_output.outputs.RELEASE_NAME }}
           tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
@@ -105,46 +110,53 @@ jobs:
           file_pattern: build.md *-update.json
           commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
 
-      - name: Report to Telegram
-        env:
-          TG_TOKEN: ${{ secrets.TG_TOKEN }}
-        if: env.TG_TOKEN != null
-        run: |
-          cd build || echo "build folder not found"
+  notify:
+    needs: run
+    uses: ./.github/workflows/notify.yml
+    if: github.ref == 'refs/heads/main'
+    secrets:
+      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
+      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
+      # - name: Report to Telegram
+      #   env:
+      #     TG_TOKEN: ${{ secrets.TG_TOKEN }}
+      #   if: env.TG_TOKEN != null
+      #   run: |
+      #     cd build || echo "build folder not found"
 
-          TG_CHAT="@Revanced_Extended_Pro"
-          NL=$'\n'
-          APKS=""
-          MODULES=""
-          for OUTPUT in *revanced*; do
-            DL_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
-            if [[ $OUTPUT = *.apk ]]; then
-              APKS+="${NL}📦[${OUTPUT}](${DL_URL})"
-            elif [[ $OUTPUT = *.zip ]]; then
-              MODULES+="${NL}📦[${OUTPUT}](${DL_URL})"
-            fi
-          done
-          MODULES=${MODULES#"$NL"}
-          APKS=${APKS#"$NL"}
+      #     TG_CHAT="@rvc_magisk"
+      #     NL=$'\n'
+      #     APKS=""
+      #     MODULES=""
+      #     for OUTPUT in *revanced*; do
+      #       DL_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
+      #       if [[ $OUTPUT = *.apk ]]; then
+      #         APKS+="${NL}📦[${OUTPUT}](${DL_URL})"
+      #       elif [[ $OUTPUT = *.zip ]]; then
+      #         MODULES+="${NL}📦[${OUTPUT}](${DL_URL})"
+      #       fi
+      #     done
+      #     MODULES=${MODULES#"$NL"}
+      #     APKS=${APKS#"$NL"}
 
-          BODY="$(sed 's/^\* \*\*/↪ \*\*/g; s/^\* `/↪ \*\*/g; s/`/\*/g; s/^\* /\↪/g; s/\*\*/\*/g; s/###//g;' ../build.md)"
-          MSG="*New build!*
+      #     BODY="$(sed 's/^\* \*\*/↪ \*\*/g; s/^\* `/↪ \*\*/g; s/`/\*/g; s/^\* /\↪/g; s/\*\*/\*/g; s/###//g;' ../build.md)"
+      #     MSG="*New build!*
 
-          ${BODY}
+      #     ${BODY}
 
-          *▼ Download Links:*
-          Modules:
-          ${MODULES}
+      #     *▼ Download Links:*
+      #     Modules:
+      #     ${MODULES}
 
-          APKs:
-          ${APKS}
-          "
-          echo "'$MSG'"
-          POST="https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
-          curl -X POST --data-urlencode "parse_mode=Markdown" --data-urlencode "text=${MSG}" --data-urlencode "chat_id=${TG_CHAT}" "$POST"
+      #     APKs:
+      #     ${APKS}
+      #     "
+      #     echo "'$MSG'"
+      #     POST="https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
+      #     curl -X POST --data-urlencode "parse_mode=Markdown" --data-urlencode "text=${MSG}" --data-urlencode "chat_id=${TG_CHAT}" "$POST"
 
-      - uses: actions/upload-artifact@v3
-        with:
-          name: logs
-          path: logs
-          if-no-files-found: ignore
+      # - uses: actions/upload-artifact@v3
+      #   with:
+      #     name: logs
+      #     path: logs
+      #     if-no-files-found: ignore
